composer_keep_updated: true
apt_cache_valid_time: 3600
php_max_execution_time: 700
upload_max_filesize : 300M
upload_max_size: 300M
php_upload_max_filesize: 300M
php_post_max_size: 300M
apt_package_state: present
apt_security_package_state: latest
apt_dev_package_state: latest
ntp_timezone: Etc/UTC
ntp_manage_config: true
ssh_client_ip_lookup: false
php_memory_limit: 768M
php_max_input_time: 1000
php_extensions_custom:
  php7.4-soap: "{{ apt_package_state }}"
  php-imagick: "{{ apt_package_state }}"
letsencrypt_contact_emails:
  - dsemblano@gmail.com
www_root: /srv/www

# Values of raw_vars will be wrapped in `{% raw %}` to avoid templating problems if values include `{%` and `{{`.
# Will recurse dicts/lists. `*` is wildcard for one or more dict keys, list indices, or strings. Example:
#   - vault_wordpress_sites.*.*_salt    -- matches vault_wordpress_sites.example.com.env.secure_auth_salt etc.
# Will not function for var names or topmost dict keys that contain a period ('.').
raw_vars:
  - vault_mail_password
  - vault_mysql_root_password
  - vault_users.*.password
  - vault_users.*.salt
  - vault_wordpress_env_defaults
  - vault_wordpress_sites
