# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  tijolocwb.com.br:
    site_hosts:
    - canonical: tijolocwb.test
      redirects:
      - www.tijolocwb.test
    local_path: ../site
    admin_email: admin@tijolocwb.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
