# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  tijolocwb.com.br:
    site_hosts:
    - canonical: staging.tijolocwb.com.br
      # redirects:
      # - www.tijolocwb.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/vinhosnico.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
